//! Read-only escape diagnostics on states already present in FutureGraph.
//!
//! A selected MAX/MIN path is ONE observed line, never a universal safety
//! certificate. No new joint actions, states, or opponent predictions are
//! generated by this module.

use std::time::Instant;

use crate::search::forecast::ForecastCertainty;
use crate::search::graph::FutureGraph;
use crate::search::path::FuturePath;
use crate::simulation::mobility::MobilityAnalysis;
use crate::simulation::state::SimulatedGameState;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum EscapeEvidenceQuality {
    /// All legal responses were examined in the completed depth and food
    /// remained deterministic. This qualifies the search, not the single
    /// representative path as a proven escape strategy.
    CompleteDeterministic,
    /// Search responses were complete but future food was uncertain.
    CompleteConditionalFood,
    /// The representative line may omit alpha-beta-pruned responses.
    Partial,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct EscapeSnapshot {
    pub(crate) immediate_exits: u8,
    /// One or more immediately legal exits can be entered by a rival with
    /// equal or greater length on the same turn. This is a threat, not proof.
    pub(crate) contested_exits: u8,
    pub(crate) observed_dead: bool,
}

impl EscapeSnapshot {
    pub(crate) fn from_state(state: &SimulatedGameState) -> Option<Self> {
        let ours = state.snake(&state.our_snake_id)?;
        if !ours.alive {
            return Some(Self {
                immediate_exits: 0,
                contested_exits: 0,
                observed_dead: true,
            });
        }
        let head = ours.head()?;
        let mobility = MobilityAnalysis::from_state(state);
        let legal = mobility.deterministic_moves_for(state, &state.our_snake_id);
        let mut contested = 0_u8;
        for our_direction in legal.iter() {
            let destination = our_direction.apply(head);
            let enemy_can_contest = state
                .snakes
                .iter()
                .filter(|enemy| {
                    enemy.alive && enemy.id != state.our_snake_id && enemy.length() >= ours.length()
                })
                .filter_map(|enemy| enemy.head().map(|enemy_head| (enemy, enemy_head)))
                .any(|(enemy, enemy_head)| {
                    mobility
                        .deterministic_moves_for(state, &enemy.id)
                        .iter()
                        .any(|direction| direction.apply(enemy_head) == destination)
                });
            if enemy_can_contest {
                contested = contested.saturating_add(1);
            }
        }
        Some(Self {
            immediate_exits: u8::try_from(legal.len()).unwrap_or(u8::MAX),
            contested_exits: contested,
            observed_dead: false,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct EscapeEvidence {
    /// Number of already-generated states inspected; no generated edges.
    pub(crate) observed_states: u8,
    pub(crate) minimum_exits: u8,
    pub(crate) first_narrow_ply: Option<u8>,
    pub(crate) first_contested_ply: Option<u8>,
    pub(crate) first_no_exit_ply: Option<u8>,
    pub(crate) first_observed_death_ply: Option<u8>,
    pub(crate) quality: EscapeEvidenceQuality,
}

impl EscapeEvidence {
    /// Inspect one retained minimax trajectory at a fixed completed depth.
    /// "Complete" only applies to the search response coverage supplied by
    /// its caller; the trajectory is not a certificate of universal survival.
    pub(crate) fn from_graph_path(
        graph: &FutureGraph,
        path: &FuturePath,
        certainty: ForecastCertainty,
        adversarially_complete: bool,
        deadline: Instant,
    ) -> Option<Self> {
        const MAX_OBSERVED_STATES: usize = 12;
        let mut ids = vec![graph.root()];
        let mut previous = graph.root();
        let mut connected = true;
        path.for_each_step(|step| {
            if !connected || step.node != previous {
                connected = false;
            } else {
                ids.push(step.child);
                previous = step.child;
            }
        });
        if !connected || ids.len() > MAX_OBSERVED_STATES {
            return None;
        }

        let quality = if !adversarially_complete {
            EscapeEvidenceQuality::Partial
        } else if certainty.is_provisional() {
            EscapeEvidenceQuality::CompleteConditionalFood
        } else {
            EscapeEvidenceQuality::CompleteDeterministic
        };
        let mut result = Self {
            observed_states: 0,
            minimum_exits: u8::MAX,
            first_narrow_ply: None,
            first_contested_ply: None,
            first_no_exit_ply: None,
            first_observed_death_ply: None,
            quality,
        };
        for (ply, id) in ids.into_iter().enumerate() {
            if Instant::now() >= deadline {
                return None;
            }
            let snapshot = EscapeSnapshot::from_state(&graph.node(id).state)?;
            let ply = u8::try_from(ply).ok()?;
            result.observed_states = result.observed_states.saturating_add(1);
            result.minimum_exits = result.minimum_exits.min(snapshot.immediate_exits);
            if snapshot.immediate_exits <= 1 {
                result.first_narrow_ply.get_or_insert(ply);
            }
            if snapshot.immediate_exits == 0 {
                result.first_no_exit_ply.get_or_insert(ply);
            }
            if snapshot.contested_exits > 0 {
                result.first_contested_ply.get_or_insert(ply);
            }
            if snapshot.observed_dead {
                result.first_observed_death_ply.get_or_insert(ply);
            }
        }
        Some(result)
    }
}

#[cfg(test)]
mod tests {
    use std::time::{Duration, Instant};

    use super::*;
    use crate::analysis::replay_fixtures::late_seed_20261003;

    #[test]
    fn seed_20261003_last_escape_is_contested_by_larger_hobbs() {
        let final_state = late_seed_20261003(333);
        let observation = EscapeSnapshot::from_state(&final_state).unwrap();
        assert_eq!(observation.immediate_exits, 1);
        assert_eq!(observation.contested_exits, 1);
        assert!(!observation.observed_dead);
    }

    #[test]
    fn seed_20261003_detects_narrowing_before_final_collision() {
        let early = EscapeSnapshot::from_state(&late_seed_20261003(325)).unwrap();
        let late = EscapeSnapshot::from_state(&late_seed_20261003(333)).unwrap();
        assert!(early.immediate_exits > late.immediate_exits);
    }

    #[test]
    fn inspection_does_not_expand_the_future_graph_or_pretend_to_prove_safety() {
        let graph = FutureGraph::new_beam(late_seed_20261003(333));
        let nodes = graph.node_count();
        let edges = graph.edge_count();
        let path = FuturePath::empty();
        let evidence = EscapeEvidence::from_graph_path(
            &graph,
            &path,
            ForecastCertainty::FoodProvisional,
            false,
            Instant::now() + Duration::from_secs(1),
        )
        .unwrap();
        assert_eq!(evidence.quality, EscapeEvidenceQuality::Partial);
        assert_eq!(evidence.first_narrow_ply, Some(0));
        assert_eq!(evidence.first_contested_ply, Some(0));
        assert_eq!(evidence.observed_states, 1);
        assert_eq!(graph.node_count(), nodes);
        assert_eq!(graph.edge_count(), edges);
    }

    #[test]
    fn complete_path_with_provisional_food_is_not_deterministic() {
        let graph = FutureGraph::new_beam(late_seed_20261003(325));
        let path = FuturePath::empty();
        let deadline = Instant::now() + Duration::from_secs(1);
        let evidence = EscapeEvidence::from_graph_path(
            &graph,
            &path,
            ForecastCertainty::FoodProvisional,
            true,
            deadline,
        )
        .unwrap();
        assert_eq!(
            evidence.quality,
            EscapeEvidenceQuality::CompleteConditionalFood
        );
    }
}
