//! Captured states from the LOCAL GitHub Actions duel, seed 20261003.
//! Actual body order, health and food are retained; no invented geometry.
use crate::simulation::state::{RulesContext, SimulatedGameState, SimulatedSnake};
use crate::Coord;

type RecordedCoordinates<'a> = (
    i32,
    i32,
    &'a [(i32, i32)],
    &'a [(i32, i32)],
    &'a [(i32, i32)],
);

pub(super) fn state(turn: i32) -> SimulatedGameState {
    let (our_health, enemy_health, ours, enemy, food): RecordedCoordinates<'_> = match turn {
        231 => (
            100,
            88,
            &[
                (10, 3),
                (9, 3),
                (9, 4),
                (8, 4),
                (7, 4),
                (6, 4),
                (6, 5),
                (7, 5),
                (8, 5),
                (8, 6),
                (7, 6),
                (7, 7),
                (6, 7),
                (6, 8),
                (5, 8),
                (4, 8),
                (3, 8),
                (2, 8),
                (2, 7),
                (3, 7),
                (3, 7),
            ],
            &[
                (0, 1),
                (0, 0),
                (1, 0),
                (2, 0),
                (2, 1),
                (3, 1),
                (3, 2),
                (4, 2),
                (4, 1),
                (4, 0),
                (5, 0),
                (5, 1),
                (5, 2),
                (6, 2),
                (6, 1),
                (7, 1),
                (7, 2),
                (7, 3),
                (8, 3),
                (8, 2),
                (8, 1),
            ],
            &[(1, 1), (6, 0), (7, 10), (0, 10), (4, 7)],
        ),
        232 => (
            99,
            100,
            &[
                (10, 2),
                (10, 3),
                (9, 3),
                (9, 4),
                (8, 4),
                (7, 4),
                (6, 4),
                (6, 5),
                (7, 5),
                (8, 5),
                (8, 6),
                (7, 6),
                (7, 7),
                (6, 7),
                (6, 8),
                (5, 8),
                (4, 8),
                (3, 8),
                (2, 8),
                (2, 7),
                (3, 7),
            ],
            &[
                (1, 1),
                (0, 1),
                (0, 0),
                (1, 0),
                (2, 0),
                (2, 1),
                (3, 1),
                (3, 2),
                (4, 2),
                (4, 1),
                (4, 0),
                (5, 0),
                (5, 1),
                (5, 2),
                (6, 2),
                (6, 1),
                (7, 1),
                (7, 2),
                (7, 3),
                (8, 3),
                (8, 2),
                (8, 2),
            ],
            &[(6, 0), (7, 10), (0, 10), (4, 7), (4, 10)],
        ),
        235 => (
            96,
            97,
            &[
                (9, 0),
                (10, 0),
                (10, 1),
                (10, 2),
                (10, 3),
                (9, 3),
                (9, 4),
                (8, 4),
                (7, 4),
                (6, 4),
                (6, 5),
                (7, 5),
                (8, 5),
                (8, 6),
                (7, 6),
                (7, 7),
                (6, 7),
                (6, 8),
                (5, 8),
                (4, 8),
                (3, 8),
            ],
            &[
                (1, 4),
                (1, 3),
                (1, 2),
                (1, 1),
                (0, 1),
                (0, 0),
                (1, 0),
                (2, 0),
                (2, 1),
                (3, 1),
                (3, 2),
                (4, 2),
                (4, 1),
                (4, 0),
                (5, 0),
                (5, 1),
                (5, 2),
                (6, 2),
                (6, 1),
                (7, 1),
                (7, 2),
                (7, 3),
            ],
            &[(6, 0), (7, 10), (0, 10), (4, 7), (4, 10)],
        ),
        241 => (
            97,
            91,
            &[
                (6, 3),
                (6, 2),
                (6, 1),
                (6, 0),
                (7, 0),
                (8, 0),
                (9, 0),
                (10, 0),
                (10, 1),
                (10, 2),
                (10, 3),
                (9, 3),
                (9, 4),
                (8, 4),
                (7, 4),
                (6, 4),
                (6, 5),
                (7, 5),
                (8, 5),
                (8, 6),
                (7, 6),
                (7, 7),
            ],
            &[
                (4, 5),
                (4, 4),
                (3, 4),
                (2, 4),
                (2, 5),
                (1, 5),
                (1, 4),
                (1, 3),
                (1, 2),
                (1, 1),
                (0, 1),
                (0, 0),
                (1, 0),
                (2, 0),
                (2, 1),
                (3, 1),
                (3, 2),
                (4, 2),
                (4, 1),
                (4, 0),
                (5, 0),
                (5, 1),
            ],
            &[(7, 10), (0, 10), (4, 7), (4, 10), (0, 8)],
        ),
        242 => (
            96,
            90,
            &[
                (7, 3),
                (6, 3),
                (6, 2),
                (6, 1),
                (6, 0),
                (7, 0),
                (8, 0),
                (9, 0),
                (10, 0),
                (10, 1),
                (10, 2),
                (10, 3),
                (9, 3),
                (9, 4),
                (8, 4),
                (7, 4),
                (6, 4),
                (6, 5),
                (7, 5),
                (8, 5),
                (8, 6),
                (7, 6),
            ],
            &[
                (4, 6),
                (4, 5),
                (4, 4),
                (3, 4),
                (2, 4),
                (2, 5),
                (1, 5),
                (1, 4),
                (1, 3),
                (1, 2),
                (1, 1),
                (0, 1),
                (0, 0),
                (1, 0),
                (2, 0),
                (2, 1),
                (3, 1),
                (3, 2),
                (4, 2),
                (4, 1),
                (4, 0),
                (5, 0),
            ],
            &[(7, 10), (0, 10), (4, 7), (4, 10), (0, 8), (5, 5)],
        ),
        _ => panic!("unrecorded turn"),
    };
    let convert = |points: &[(i32, i32)]| {
        points
            .iter()
            .map(|&(x, y)| Coord { x, y })
            .collect::<Vec<_>>()
    };
    SimulatedGameState {
        turn,
        width: 11,
        height: 11,
        food: convert(food),
        hazards: Vec::new(),
        snakes: vec![
            SimulatedSnake {
                id: "ours".into(),
                health: our_health,
                body: convert(ours),
                alive: true,
            },
            SimulatedSnake {
                id: "hobbs".into(),
                health: enemy_health,
                body: convert(enemy),
                alive: true,
            },
        ],
        our_snake_id: "ours".into(),
        rules: RulesContext {
            name: "standard".into(),
            max_health: 100,
            hazard_damage_per_turn: 0,
        },
    }
}

#[test]
fn recorded_lengths_and_heads_are_consistent() {
    for turn in [231, 232, 235, 241, 242] {
        let s = state(turn);
        assert_eq!(s.snakes.len(), 2);
        assert!(s.snakes.iter().all(|snake| snake.alive && snake.health > 0));
        assert_eq!(s.snakes[0].body.len(), if turn < 241 { 21 } else { 22 });
        assert_eq!(s.snakes[1].body.len(), if turn == 231 { 21 } else { 22 });
    }
    assert_eq!(state(241).snakes[0].head(), Some(Coord { x: 6, y: 3 }));
    assert_eq!(state(242).snakes[0].head(), Some(Coord { x: 7, y: 3 }));
}
